services:
  ### Microservices ###

  # Users service
  users-service:
    container_name: users-service
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - internal
    expose:
      - "8081"
    depends_on:
      - customersdb
      - kafka
    environment:
      - DB_ADDRESS=jdbc:postgresql://customersdb:5432/usersdb
      - DB_USER=user
      - DB_PASSWORD=secret
    restart: unless-stopped

  # Cinemas service
  cinemas-service:
    container_name: cinemas-service
    build:
      context: ./cinemas
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - internal
    expose:
      - "8082"
    depends_on:
      - cinemasdb
      - kafka
    restart: unless-stopped

  # Screenings service
  screenings-service:
    container_name: screenings-service
    build:
      context: ./screenings
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - internal
    environment:
      - DB_ADDRESS=jdbc:postgresql://screeningsdb:5432/screeningsdb
      - DB_USER=user
      - DB_PASSWORD=secret
      - MOVIES_SERVICE_URL=http://movies-service:8086/movies
      - CINEMAS_SERVICE_URL=http://cinemas-service:8082/cinemas
      - PRICING_SERVICE_URL=http://pricing-service:8087/api/v1/pricing
      - KAFKA_ADDRESS=kafka:9092
      - KAFKA_GROUP_ID=screenings-group
    expose:
      - "8083"
    depends_on:
      - screeningsdb
      - kafka
    restart: unless-stopped

  # Reservations service
  reservations-service:
    container_name: reservations-service
    build:
      context: ./reservations
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - internal
    environment:
      - DATABASE_URL=jdbc:postgresql://reservationsdb:5432/reservationsdb
      - DATABASE_USER=user
      - DATABASE_PASSWORD=secret
      - SCREENINGS_URL=http://screenings-service:8083/screenings
      - CINEMAS_URL=http://cinemas-service:8082
      - KAFKA_ADDRESS=kafka:9092
      - KAFKA_GROUP_ID=reservations-group
    expose:
      - "8084"
    depends_on:
      - reservationsdb
      - kafka
    restart: unless-stopped

  # Payments service
  payments-service:
    build:
      context: ./payments
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - internal
    expose:
      - "8085"
    environment:
      - KAFKA_ADDRESS=kafka:9092
      - KAFKA_GROUP_ID=payments-group
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=paymentsdb
      - DB_HOST=paymentsdb
    depends_on:
      - paymentsdb
      - kafka
    restart: unless-stopped


  # Pricing service
  pricing-service:
    container_name: pricing-service
    build:
      context: ./pricing
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    networks:
      - internal
    expose:
      - "8087"
    depends_on:
      - kafka
    restart: unless-stopped

  # Notifications service
  notifications-service:
    container_name: notifications-service
    build:
      context: ./notifications
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - internal
    depends_on:
      - kafka
    restart: unless-stopped

  ### Databases ###

  # Customers Database
  customersdb:
    container_name: customersdb
    image: postgres:latest
    environment:
      - POSTGRES_ROOT_PASSWORD=secret
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=usersdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - internal
    expose:
      - "5432"
    restart: unless-stopped

  # Payments Database
  paymentsdb:
    container_name: paymentsdb
    image: postgres:latest
    environment:
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=paymentsdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5445:5432"
    expose:
      - "5445"
    networks:
      - internal
    restart: unless-stopped

  # Screenings Database
  screeningsdb:
    container_name: screeningsdb
    image: postgres:latest
    environment:
      - POSTGRES_ROOT_PASSWORD=secret
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=screeningsdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5443:5432"
    expose:
      - "5443"
    networks:
      - internal
    restart: unless-stopped

  # Reservations Database
  reservationsdb:
    container_name: reservationsdb
    image: postgres:latest
    environment:
      - POSTGRES_ROOT_PASSWORD=secret
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=reservationsdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5444:5432"
    expose:
      - "5444"
    networks:
      - internal
    restart: unless-stopped

  # Cinemas Database
  cinemasdb:
    container_name: cinemasdb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_DATABASE=cinemasdb
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - internal
    expose:
      - "3306"
    restart: unless-stopped

  # Movies Database
  moviesdb:
    container_name: moviesdb
    image: postgres:latest
    environment:
      - POSTGRES_ROOT_PASSWORD=secret
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=moviesdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5453:5432"
    expose:
      - "5453"
    networks:
      - internal
    restart: unless-stopped

    ### Database Management Tools ###
    # MySQL Admin
  mysqladmin:
    container_name: mysqladmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: cinemasdb
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: secret
    ports:
      - "8001:80"
    networks:
      - internal
    restart: unless-stopped

    # PostgreSQL Admin page
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - internal
    restart: unless-stopped

  ### Apache Kafka ###
  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:  # Dodaj tę sekcję
      - internal

  # Apache Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - "9092"
    depends_on:
      - zookeeper
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mysql: