# Server port - default 8400
server:
  port: ${PORT:8400}

spring:
  # DataSource configuration
  datasource:
    hikari:
      jdbc-url: ${DATABASE_URL:jdbc:postgresql://localhost:5444/reservationsdb}
      username: ${DATABASE_USER:user}
      password: ${DATABASE_PASSWORD:secret}
      driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5444/reservationsdb}
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:secret}
  # Spring JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Spring Profiles
  profiles:
    active: ${PROFILE:default}

# Kafka configuration
  kafka:
    bootstrap-servers: ${KAFKA_ADDRESS:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:reservations-group}


# External microservices URLs
services:
  url:
    screenings: ${SCREENINGS_URL:http://localhost:8008/screenings}
    cinemas: ${CINEMAS_URL:http://localhost:8005}