# Server port - default 8400
server:
  port: 8400

spring:
  # Spring JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Spring Cloud configuration
  cloud:
    vault:
      kv:
        enabled: false
      enabled: false
  # Spring Profiles
  profiles:
    active: test

# External microservices URLs
services:
  url:
    screenings: ${SCREENINGS_URL:http://localhost:8006/screenings}
    cinemas: ${CINEMAS_URL:http://localhost:8005}
    users: ${USERS_URL:http://localhost:8081/users}