spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    driverClassName: org.postgresql.Driver
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:5432/usersdb
    user: user
    password: secret
    clean-disabled: false
    clean-on-validation-error: true
server:
  port: 8080
  servlet:
    context-path: /users