spring:
  application:
    name: customer-service
  cloud:
    vault:
      enabled: false
      kv:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    driverClassName: org.postgresql.Driver
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/usersdb
    user: user
    password: secret

server:
  port: 8080
  servlet:
    context-path: /users

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/