spring:
  application:
    name: customer-service
  cloud:
    vault:
      enabled: false
      kv:
        enabled: false
  datasource:
    url: ${DB_ADDRESS:jdbc:postgresql://localhost:5432/usersdb}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${DB_ADDRESS:jdbc:postgresql://localhost:5432/usersdb}
    user: ${DB_USER:user}
    password: ${DB_PASSWORD:secret}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /users

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}