spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    driverClassName: org.postgresql.Driver
    username: user
    password: secret
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/usersdb
    user: user
    password: secret
server:
  port: 8080
  servlet:
    context-path: /users