spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect