# Spring application properties
spring:
  application:
    name: screenings-service

# Server properties
server:
  port: 8006
  servlet:
    context-path: /screenings

# Eureka Client configuration
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/