# Spring application properties
spring:
  application:
    name: screenings-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  kafka:
    consumer:
      group-id: ${KAFKA_GROUP_ID:screenings-group}
    bootstrap-servers: ${KAFKA_ADDRESS:localhost:9092}

# Server properties
server:
  port: 8008
  servlet:
    context-path: /screenings

# Database configuration
app:
  db:
    address: ${DB_ADDRESS:jdbc:postgresql://localhost:5443/screeningsdb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:secret}

# Movies service configuration
movies:
  service:
    url: ${MOVIES_SERVICE_URL:http://localhost:8000/movies}

# Cinemas service configuration
cinemas:
  service:
    url: ${CINEMAS_SERVICE_URL:http://localhost:8005/cinemas}

pricing:
    service:
        url: ${PRICING_SERVICE_URL:http://localhost:8001/api/v1/pricing}

# Eureka Client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}