spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service
            uri: ${CUSTOMER_SERVICE_URI:http://localhost:8081}
            predicates:
              - Path=/customers/**
            filters:
              - AddResponseHeader=X-Response-Default-Foo, Default-Bar
          - id: cinemas-service
            uri: ${CINEMAS_SERVICE_URI:http://localhost:8005/cinemas}
            predicates:
              - Path=/cinemas/**
            filters:
              - AddRequestHeader=X-Request-Default-Foo, Default-Bar
              - AddResponseHeader=X-Response-Default-Foo, Default-Bar

