spring:
  application:
    name: cinemas-service
  datasource:
    url: jdbc:mysql://localhost:3306/cinemasdb
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/cinemasdb
    user: root
    password: secret

  cloud:
    vault:
      uri: ${VAULT_ADDR:http://127.0.0.1:8200}
      token: ${VAULT_TOKEN:root-token}
      kv:
        enabled: true
        backend: secret
        application-name: cinemas-service
      authentication: token
  profiles:
    active: dev

server:
  port: 8005
  servlet:
    context-path: /cinemas

eureka:
  client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/