spring:
  application:
    name: cinemas-service
  datasource:
    url: ${DB_ADDRESS:jdbc:mysql://localhost:3306/cinemasdb}
    username: user
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${DB_ADDRESS:jdbc:mysql://localhost:3306/cinemasdb}
    user: user
    password: secret

server:
  port: ${PORT:8005}
  servlet:
    context-path: /cinemas

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

googlemaps:
  api-key: ${GOOGLE_MAPS_API_KEY}