spring:
  # Application properties
  application:
    name: cinemas-service

  # Datasource properties
  datasource:
    url: ${DB_ADDRESS:jdbc:mysql://localhost:3306/cinemasdb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Flyway properties
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${DB_ADDRESS:jdbc:mysql://localhost:3306/cinemasdb}
    user: ${DB_USER:user}
    password: ${DB_PASSWORD:secret}

server:
  port: ${PORT:8005}
  servlet:
    context-path: /cinemas

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

googlemaps:
  api-key: ${GOOGLE_MAPS_API_KEY}

logging:
  level:
    com.movieapp.cinemas: ${LOGGING_LEVEL:debug}