spring:
  application:
    name: cinemas-service
  datasource:
    url: ${DB_ADDRESS:jdbc:mysql://localhost:3306/cinemasdb}
    username: user
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${DB_ADDRESS:jdbc:mysql://localhost:3306/cinemasdb}
    user: user
    password: secret

  cloud:
    vault:
      uri: ${VAULT_ADDR:http://127.0.0.1:8200}
      token: ${VAULT_TOKEN:root-token}
      kv:
        enabled: true
        backend: secret
        application-name: cinemas-service
      authentication: token

vault:
  host: ${VAULT_ADDR:http://127.0.0.1}
  port: ${VAULT_PORT:8200}

server:
  port: 8005
  servlet:
    context-path: /cinemas

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}