spring:
  application:
    name: cinemas-service
  data:
    mongodb:
      uri: 'mongodb://root:example@localhost:27017/cinemasdb'
      username: root
      password: example
server:
  port: 8001
  servlet:
    context-path: /cinemas