# Spring framework properties
spring:
  application:
    name: notifications-service
  kafka:
    bootstrap-servers: localhost:9092

# Server properties
server:
  port: ${PORT:8400}
  servlet:
    context-path: /notifications

# Mailing provider properties
mailing:
  api-key: ${SEND_GRID_API_KEY}